### ISSUE TITLE
Any chance for part 2?

### ISSUE THREAD

**Issue by hiltonc** [ole/GestureRecognition#1]
http://oleb.net/blog/2012/01/gesture-recognition-on-ios-with-attention-to-detail/ was great, thank you! It teases about a part 2 on adding momentum, but I can't find it on your blog... any chance you still plan to write it up, or that I missed it?

**Comment by ole** [comment]
Yeah, sorry about that. I never wrote part 2, so you didn't miss it. It sort of became obsolete with the introduction of UIKit Dynamics.

**Comment by hiltonc** [comment]
Cool, I'll look into that. I just Googled a bit and didn't find anything too promising but I'll keep looking. Thanks!
